Add version check and polish
Copied from https://github.com/privacy-scaling-explorations/halo2curves/pull/59

diff --git a/.github/workflows/release-pr.yml b/.github/workflows/release-pr.yml
--- a/.github/workflows/release-pr.yml
+++ b/.github/workflows/release-pr.yml
@@ -7,11 +7,43 @@ on:
         required: true
         type: string
 
+env:
+  RUSTUP_MAX_RETRIES: 10
+
 jobs:
   make-release-pr:
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        package: [neptune]
     steps:
       - uses: actions/checkout@v3
+      - uses: actions-rs/toolchain@v1
+        with:
+            profile: minimal
+      - name: Get current version
+        id: get-version
+        run: |
+          echo "CURRENT_VERSION=$(./script/get_current_version.sh ${{ matrix.package }})" >> $GITHUB_ENV
+      - name: Check version
+        id: version-check
+        run: |
+          IFS='.' read -ra INPUT_VERSION <<< "${{ github.event.inputs.version }}"
+          IFS='.' read -ra CURRENT_VERSION <<< "${{ env.CURRENT_VERSION }}"
+
+          for i in "${!INPUT_VERSION[@]}"; do
+            if (( INPUT_VERSION[i] > CURRENT_VERSION[i] )); then
+              echo "Input version is larger than current version. Proceeding..."
+              exit 0
+            elif (( INPUT_VERSION[i] < CURRENT_VERSION[i] )); then
+              echo "Input version is not larger than current version. Failing..."
+              exit 1
+            fi
+          done
+
+          echo "Input version is equal to current version. Failing..."
+          exit 1
+
       - name: Install cargo-release
         uses: taiki-e/install-action@v2
         with:
@@ -21,4 +53,5 @@ jobs:
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           version: ${{ inputs.version }}
+          pr-template-file: .github/release-pr-template.ejs
           crate-name: "neptune" 
